SET IDENTITY_INSERT [dbo].[GroceryItem] ON
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (1, N'Fantasy Crunchy Choco Chip Cookies', 100, N'Delicious crunchy choco chip cookies.', CAST(26.69 AS Decimal(18, 2)), N'/images/chocochip.png', 10, N'Jul 10 2024  6:06PM', N'Snacks')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (2, N'Peanut Butter Bite Premium Butter Cookies', 100, N'Premium butter cookies with peanut butter.', CAST(26.69 AS Decimal(18, 2)), N'/images/peanut.png', 15, N'Jul 10 2024  6:06PM', N'Snacks')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (3, N'Yumitos Chilli Sprinkled Potato Chips', 100, N'Spicy chilli sprinkled potato chips.', CAST(26.69 AS Decimal(18, 2)), N'/images/chips.png', 20, N'Jul 10 2024  6:06PM', N'Snacks')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (4, N'Healthy Long Life Toned Milk', 100, N'Healthy long life toned milk.', CAST(26.69 AS Decimal(18, 2)), N'/images/milk1l.png', 5, N'Jul 10 2024  6:06PM', N'')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (5, N'Raw Mutton Leg, Packaging 5 Kg', 100, N'Fresh raw mutton leg, 5 Kg packaging.', CAST(26.69 AS Decimal(18, 2)), N'/images/beef.png', 25, N'Jul 10 2024  6:06PM', N'')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (6, N'Cold Brew Coffee Instant Coffee', 100, N'Instant cold brew coffee.', CAST(26.69 AS Decimal(18, 2)), N'/images/coffee.png', 30, N'Jul 10 2024  6:06PM', N'')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (7, N'SnackAmor Combo Pack of Jowar Stick and Jowar Chips', 100, N'Combo pack of Jowar stick and chips.', CAST(26.69 AS Decimal(18, 2)), N'/images/snackarmor.png', 35, N'Jul 10 2024  6:06PM', N'')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (8, N'Neu Farm Unpolished Desi Toor Dal', 100, N'Unpolished Desi Toor Dal.', CAST(26.69 AS Decimal(18, 2)), N'/images/neufarm.png', 40, N'Jul 10 2024  6:06PM', N'')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (9, N'Dog Treats Natural Yak Milk Bars For Small Dogs', 100, N'Natural Yak Milk Bars for small dogs.', CAST(26.69 AS Decimal(18, 2)), N'/images/dogfood.png', 45, N'Jul 10 2024  6:06PM', N'')
INSERT INTO [dbo].[GroceryItem] ([Id], [Name], [Quantity], [Description], [Price], [ImageUrl], [Discount], [CreatedDate], [Category]) VALUES (10, N'Blended Instant Coffee 50 g Buy 1 Get 1 Free', 100, N'Blended instant coffee, buy 1 get 1 free.', CAST(26.69 AS Decimal(18, 2)), N'/images/coffee1get1.png', 50, N'Jul 10 2024  6:06PM', N'')
SET IDENTITY_INSERT [dbo].[GroceryItem] OFF
